[package]
name = "swagger-js-codegen-with-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[example]]
name = "rendering"

[dependencies]
rustache = "^0.1"
